// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaMVC.Data;

#nullable disable

namespace PruebaMVC.Migrations
{
    [DbContext(typeof(PruebaMVCContext))]
    [Migration("20230926213548_pruebadefBools")]
    partial class pruebadefBools
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PruebaMVC.Models.Personas", b =>
                {
                    b.Property<string>("codPersona")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("apMaternoPersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apPaternoPersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ciPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("direccionPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaNacPewsona")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActivo")
                        .HasColumnType("bit");

                    b.Property<string>("mailPersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombrePersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("passwordPersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userPersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codPersona");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("PruebaMVC.Models.Usuarios", b =>
                {
                    b.Property<string>("codUsuario")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonacodPersona")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("codPersona")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("configuracionUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codUsuario");

                    b.HasIndex("PersonacodPersona");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PruebaMVC.Models.Usuarios", b =>
                {
                    b.HasOne("PruebaMVC.Models.Personas", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonacodPersona")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });
#pragma warning restore 612, 618
        }
    }
}
