CREATE TABLE Empresas(
	id INT IDENTITY(1, 1),
	CodEMP VARCHAR(45) NOT NULL PRIMARY KEY,
	NombreEMP VARCHAR(150) NOT NULL,
	CreatedAt TIMESTAMP NOT NULL,
	LastUpdate TIMESTAMP NOT NULL,
	
);

CREATE TABLE Personas(
	id INT IDENTITY(1, 1),
	CodPER VARCHAR(45) NOT NULL PRIMARY KEY,
	NombrePER VARCHAR(70) NOT NULL,
	ApPaternoPER VARCHAR(70) NOT NULL,
	ApMaternoPER VARCHAR(70) NOT NULL,
	FechaNacPER VARCHAR(70) NOT NULL,
	MailPER VARCHAR(50) NOT NULL,
	CiPER VARCHAR(10) NOT NULL,

	CreatedAt TIMESTAMP NOT NULL,
	LastUpdate TIMESTAMP NOT NULL,
);

CREATE TABLE Usuarios(
	id INT IDENTITY(1, 1),
	CodUSU VARCHAR(45) NOT NULL PRIMARY KEY,
);

CREATE TABLE Personal_Empresas(
	id INT IDENTITY(1, 1),
	CodPEMP VARCHAR(45) NOT NULL PRIMARY KEY,
	CodPER FOREIGN KEY
	CONSTRAINT FK_PersonOrder FOREIGN KEY (PersonID)
    REFERENCES Persons(PersonID)

);

